version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile-local
    image: ocean
    command: bash -c 'sh /init.sh && . /etc/apache2/envvars; /usr/sbin/apache2 -DFOREGROUND' 
    volumes:
      - ./local-init.sh:/init.sh
      - ./www:/var/www/html
    links:
      - mariadb
      - redis
    depends_on:
      - mariadb
      - redis
    networks:
      - backend
      - frontend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      - 'traefik.backend=ocean'
      - 'traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}'
      - 'traefik.docker.network=frontend'
      - 'traefik.port=80'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  migration:
    image: ocean
    restart: on-failure
    command: bash -c 'chmod +x /var/www/html/migrate.sh && bash /var/www/html/migrate.sh'
    volumes:
      - ./www:/var/www/html
      - ./init.sh:/var/www/html/migrate.sh
    links:
      - mariadb
    depends_on:
      - mariadb
      - php
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      - 'traefik.enable=false'

  mariadb:
    image: mariadb:10.3
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /docker-entrypoint.sh mysqld --log-error=/var/log/mysql/err.log --general-log=1 --general-log-file=/var/log/mysql/general-log.log --character-set-server=utf8 --collation-server=utf8_general_ci"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    labels:
      - 'traefik.enable=false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  redis:
    image: redis:latest
    restart: unless-stopped
    networks:
      - backend
    labels:
      - 'traefik.enable=false'

networks:
  frontend:
    external: true
  backend:
    external: false
